name: PR Unit Test

on: [push]

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.1.app && /usr/bin/xcodebuild -version
    - name: Run tests
      run: xcodebuild test -scheme iOSCleanArchitectureWeatherApp -project iOSCleanArchitectureWeatherApp.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.0' | xcpretty && exit ${PIPESTATUS[0]}
    
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v3
    with:
            token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
            files: ./coverage1.xml,./coverage2.xml # optional
            flags: unittests # optional
            name: codecov-umbrella # optional
            fail_ci_if_error: true # optional (default = false)
            verbose: true # optional (default = false)

