name: PR Unit Test

on: [push]

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app && /usr/bin/xcodebuild -version
    - name: Run tests
      run: xcodebuild test -scheme iOSCleanArchitectureWeatherApp -project iOSCleanArchitectureWeatherApp.xcodeproj -destination "platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.2" | xcpretty && exit ${PIPESTATUS[0]}
    - name: Upload coverage results to Codecov.io
      uses: codecov/codecov-action@v2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        version: "v0.1.15"
