name: Test

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode 13
      run: sudo xcode-select -switch /Applications/Xcode_13.3.app
    - name: Run tests
      run: xcodebuild clean test -project "iOSCleanArchitectureWeatherApp.xcodeproj" -scheme "iOSCleanArchitectureWeatherApp" -destination "platform=iOS Simulator,name=iPhone 13 Pro Max,OS=latest"
    - name: Build App
      run: xcodebuild -project "iOSCleanArchitectureWeatherApp.xcodeproj" -scheme "iOSCleanArchitectureWeatherApp" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO

